version: 2
jobs:
  BuildAndDeploy:
    working_directory: ~/PierakimMarketing
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: |
            npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run-script build
      - run: npm run-script deploy
      - store_artifacts:
          path: public
workflows:
  version: 2
  build-deploy:
    jobs:
      - BuildAndDeploy:
          filters:
            branches:
              only:
                - master